version: '3.7'

services:
  web:
    build: .
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8050:8050"
    environment:
      - PORT=8050
      - API_URL=${API_URL}
      - API_LOGIN=${API_LOGIN}
      - API_PWD=${API_PWD}
      - LOGIN_CORRESPONDENCES_KEY=${LOGIN_CORRESPONDENCES_KEY}
